# your authentication token
sonar.login=3d981edde3e670b83773f712a0d8a638797b5955

# must be unique in a given SonarQube instance
sonar.projectKey=KPI_Use
# this is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=KPI_Use
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
# Comma-separated paths to directories containing source files.
# 限定要分析的路径
sonar.sources=D:/Project_all/KPI_Use

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Set the language of the source code to analyze
# 限定要分析的代??言，比如py。
# 不?置?默?分析多??言
#sonar.language = py
sonar.java.binaries=D:/Project_all/KPI_Use/target/classes